apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-sample
spec:
  replicas: 1  # 可以根据需要调整副本数量
  selector:
    matchLabels:
      app: k8s-sample
  template:
    metadata:
      labels:
        app: k8s-sample
    spec:
      containers:
        - name: k8s-sample
          image: mk100120/k8s-sample:latest  # 使用你推送到仓库中的镜像
          ports:
            - containerPort: 5005
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-sample
spec:
  selector:
    app: k8s-sample
  ports:
    - protocol: TCP
      port: 80  # 在 Kubernetes 集群内部暴露的端口
      targetPort: 8080  # 容器内部的端口
  type: LoadBalancer  # 使用 LoadBalancer 类型来暴露服务