name: k8s-sample
services:
  k8s-sample:
#    network_mode: host
    image: k8s-sample
    ports:
      - "8080:8080"
      - "5005:5005"  # 暴露调试端口
#    environment:
#      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005